SYSTARG=FreeRTOS
<../../mkconfig
SYSTARG=FreeRTOS

#Configurable parameters

CONF=emu			#default configuration
CONFLIST=emu
CLEANCONFLIST=

INSTALLDIR=$ROOT/$SYSTARG/$OBJTYPE/bin	#path of directory where kernel is installed

#end configurable parameters

#X11LIBS= -lX11 -lXext	# can remove or override using env section in config files

<$ROOT/mkfiles/mkfile-$SYSTARG-$OBJTYPE	#set vars based on target system

<| $SHELLNAME ../port/mkdevlist $CONF	#sets $IP, $DEVS, $PORT, $LIBS
<mkfile-$OBJTYPE	# sets $ARCHFILES

OBJ=\
	$ARCHFILES\
	os.$O\
	kproc-xthreads.$O\
	segflush-$OBJTYPE.$O\
	$CONF.root.$O\
	lock.$O\
	$DEVS\
	$PORT\

#	asm-$OBJTYPE.$O\

LIBNAMES=${LIBS:%=lib%.a}
#libs=${LIBS:%=$ROOT/$OBJDIR/lib/lib%.a}

HFILES=\

KERNDATE=1234567 #`{$NDATE}
CFLAGS='-DROOT="'$ROOT'"' -DEMU \
	-DTOUCHSCREEN_CAPACITIVE=$TOUCHSCREEN_CAPACITIVE \
	-I. \
	-I../port \
	-I$ROOT/$SYSTARG/$OBJTYPE/include \
	-I$ROOT/include \
	-I$ROOT/libinterp \
	-I$ROOT/libiot/vfs/include \
	-I$ROOT/libiot/include \
	$CTHREADFLAGS $CFLAGS $EMUOPTIONS
#SYSLIBS= $X11LIBS -lm -lpthread
SYSLIBS= -lm -lpthread

default:V:	$O.$CONF

$O.$CONF:	$OBJ $CONF.c $CONF.root.h $LIBNAMES
	$CC $CFLAGS '-DKERNDATE='$KERNDATE $CONF.c
	$LD $LDFLAGS -o $target $OBJ $CONF.$O $LIBFILES $SYSLIBS

install:V: $O.$CONF
	cp $O.$CONF $INSTALLDIR/$CONF

<../port/portmkfile

devfs.$O:	devfs-posix.c
